name: Data Pipeline - Import Workflow

on:
  schedule:
    - cron: '0 10 * * 0'  
jobs:
  data-import:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.3.1'  # Use a stable R version

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libcurl4-openssl-dev libssl-dev libxml2-dev build-essential gfortran

      - name: Install specific Rcpp version
        run: Rscript -e 'install.packages("Rcpp", version = "1.0.8.3", repos = "https://cran.rstudio.com")'

      - name: Install R packages with renv
        uses: r-lib/actions/setup-renv@v2
        with:
          lockfile-path: renv.lock
        env:
          RENV_PATHS_CACHE: ~/.cache/renv

      - name: Run data import script
        run: Rscript -e 'source("import-data.R")'
        env: 
          Clockify: ${{ secrets.CLOCKIFY }}
          GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

      - name: Auto-commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Auto-update: data import results"
