name: Data Import Workflow

on:
  push:
    branches: 
      - main

jobs:
  import-data:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.3.1'  # Try an alternative R version that is stable with Rcpp

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libcurl4-openssl-dev libssl-dev libxml2-dev build-essential gfortran

      - name: Manually install a specific version of Rcpp
        run: Rscript -e 'install.packages("Rcpp", version = "1.0.8.3", repos = "https://cran.rstudio.com")'
        # Alternatively, you can use renv::install("Rcpp@1.0.8.3")

      - name: Install R packages with renv
        uses: r-lib/actions/setup-renv@v2
        with:
          lockfile-path: renv.lock
        env:
          RENV_PATHS_CACHE: ~/.cache/renv

      - name: Import data
        run: Rscript -e 'source("import-data.R")'
        env: 
          Clockify: ${{ secrets.CLOCKIFY}}
      
        permissions:
        contents: write
        env:
        GITHUB_PAT: ${{ secrets.PAT }}

      - uses: stefanzweifel/git-auto-commit-action@v5
