on:
  push:
    branches: 
      - main

jobs:
  import-data:
    runs-on: ubuntu-latest
    steps:
      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install packages
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: |
            dplyr
            clockify
            lubridate
            gt

      - name: Check out repository
        uses: actions/checkout@v3

      - name: Import data
        run: Rscript -e 'source("import-data.R")'
        env: # 'env' should be used to set environment variables, and indentation needs correction
          CLOCIFY_API_Key: ${{ secrets.CLOCIFY_API_KEY }}

      - name: Commit results
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add survey_data.rds
          git commit -m 'Data updated' || echo "No changes to commit"
          git push || echo "No changes to commit"
